name: Example CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Run your build step
    - name: Run build step
      run: |
        echo "This is the build step"
        # Add your build commands here (e.g., npm install, python setup, etc.)
    
    # Custom step with your email address
    - name: Notify user at suvadipbanerjee02@gmail.com
      run: echo "Build. Notification to suvadipbanerjee02@gmail.com"
      
  test:
    runs-on: ubuntu-latest
    steps:
      - name: suvadipbanerjee02@gmail.com
        run: echo "Hello, world!"
    