name: GitHub Action for 23ff1002574@ds.study.iitm.ac.in

    on: [push]

    jobs:
      test:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v3

          - name: 23ff1002574@ds.study.iitm.ac.in
            run: echo "Hello, world!"
    